tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Azure
  template_author: Quali
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:
  vendor.resource.Azure VM From Marketplace 2G:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Image Publisher:
        type: string
        description: "The name of the Azure Image publisher. For example: “canonical”."
        tags: [user_input]

      Image Offer:
        type: string
        description: "The name of the Azure Image offer. For example: “UbuntuServer”."
        tags: [user_input]

      Image SKU:
        type: string
        description: "The version of the Azure SKU (unique system identifier of the VM created by the image). For example: “SKU: 14.04.3-LTS”."
        tags: [user_input]

      Image Version:
        type: string
        description:
        default: latest
        tags: []

      VM Size:
        type: string
        description: "The Microsoft Azure VM Size. The VM Size determines the CPU, memory, disk size and networking capacity of the VM. For example: “Standard_A1_v2”. Use the &lt;a href='https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-sizes' target='_blank'&gt;Azure documentation &lt;/a&gt; for more information, or the Azure CLI for a list of your region’s supported values: &lt;i&gt;az vm list-sizes --location “West US”&lt;/i&gt;"
        tags: [user_input]

      Disk Type:
        type: string
        description: "Type of disk to use (HDD / SSD). Default is HDD"
        default: HDD
        constraints:
          - valid_values: [HDD, SSD]
        tags: [user_input]

      Disk Size:
        type: string
        description: "Specifies the size of an empty data disk in gigabytes."
        tags: [user_input]

      Add Public IP:
        type: boolean
        default: false
        description: "Use a public IP address to communicate with the virtual machine from outside the virtual network. In most cases the public IP address is associated with the VM until it's stopped or terminated, after which it's no longer available for you to use. It's possible to reserve a public IP in Azure to ensure that the IP is available to your subscription at any time."
        tags: [user_input]

      Wait for IP:
        type: boolean
        default: false
        description: "Enables the automatic power off of an app during reservation Teardown."
        tags: [user_input]

      Extension Script file:
        type: string
        description: "The path to the script files that will be downloaded to the virtual machine. For Linux machines, it’s possible to use more than one script file. Example: https://gist.github.com/ahmetalpbalkan/b5d4a856fe15464015ae87d5587a4439/raw/466f5c30507c990a4d5a2f5c79f901fa89a80841/hello.sh"
        tags: [user_input]

      Extension Script Configurations:
        type: string
        description: "Additional information for the extension execution. For Linux machines, The command to execute, for example: python MyPythonScript.py input1 input2. For Windows machines, The PowerShell script arguments(Optional), for example: --input1 value2 –input2 value2."
        tags: [user_input]

      Extension Script Timeout:
        type: integer
        default: 1200
        description: "Extension Script Timeout in seconds"
        tags: []

      Public IP Type:
        type: string
        default: Dynamic
        description: "Static Public IP Type ensures that the VM always uses the same public IP. By default, Public IPs are dynamic and their address may change when the VM is powered off."
        constraints:
          - valid_values: [Static, Dynamic]
        tags: [user_input]

      Inbound Ports:
        type: string
        description: "Semi-colon separated list of ports and protocols to open inbound traffic from outside of the sandbox. The syntax is port[single/range]:protocol [tcp(default)/udp ].For example: “80;443:tcp;200-220:udp”"
        tags: [user_input]

      Allow all Sandbox Traffic:
        type: boolean
        default: true
        description: "Whether an app should allow inbound traffic from all other apps in the sandbox. If set to false, access from specific apps or subnets can be defined by an API call."
        tags: [user_input]

      Enable IP Forwarding:
        type: boolean
        default: false
        description: "Enables IP forwarding on all network interfaces of the app in order to support virtual appliances like routers and firewalls that are connected to multiple subnets."

    artifacts:
      icon:
        file: azure-marketplace-image-icon.png
        type: tosca.artifacts.File

  vendor.resource.Azure VM From Custom Image 2G:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Azure Image:
        type: string
        description: "Name of the custom image to be used to create a VM."
        tags: [user_input, editable_only_in_app_template]

      Azure Resource Group:
        type: string
        description: "Name of the Azure resource group that the image belongs to."
        tags: [user_input, editable_only_in_app_template]

      VM Size:
        type: string
        description: "The Microsoft Azure VM Size. The VM Size determines the CPU, memory, disk size and networking capacity of the VM. For example: “Standard_A1_v2”. Use the &lt;a href='https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-sizes' target='_blank'&gt;Azure documentation &lt;/a&gt; for more information, or the Azure CLI for a list of your region’s supported values: &lt;i&gt;az vm list-sizes --location “West US”&lt;/i&gt;"
        tags: [user_input]

      Disk Type:
        type: string
        description: "Type of disk to use (HDD / SSD). Default is HDD"
        default: HDD
        constraints:
          - valid_values: [HDD, SSD]
        tags: [user_input]

      Disk Size:
        type: string
        description: "Specifies the size of an empty data disk in gigabytes."
        tags: [user_input]

      Add Public IP:
        type: boolean
        default: false
        description: "Use a public IP address to communicate with the virtual machine from outside the virtual network. In most cases the public IP address is associated with the VM until it's stopped or terminated, after which it's no longer available for you to use. It's possible to reserve a public IP in Azure to ensure that the IP is available to your subscription at any time."
        tags: [user_input]

      Wait for IP:
        type: boolean
        default: false
        description: "Enables the automatic power off of an app during reservation Teardown."
        tags: [user_input]

      Extension Script file:
        type: string
        description: "The path to the script files that will be downloaded to the virtual machine. For Linux machines, it’s possible to use more than one script file. Example: https://gist.github.com/ahmetalpbalkan/b5d4a856fe15464015ae87d5587a4439/raw/466f5c30507c990a4d5a2f5c79f901fa89a80841/hello.sh"
        tags: [user_input]

      Extension Script Configurations:
        type: string
        description: "Additional information for the extension execution. For Linux machines, The command to execute, for example: python MyPythonScript.py input1 input2. For Windows machines, The PowerShell script arguments(Optional), for example: --input1 value2 –input2 value2."
        tags: [user_input]

      Extension Script Timeout:
        type: integer
        default: 1200
        description: "Extension Script Timeout in seconds"
        tags: []

      Public IP Type:
        type: string
        default: Dynamic
        description: "Static Public IP Type ensures that the VM always uses the same public IP. By default, Public IPs are dynamic and their address may change when the VM is powered off."
        constraints:
          - valid_values: [Static, Dynamic]
        tags: [user_input]

      Inbound Ports:
        type: string
        description: "Semi-colon separated list of ports and protocols to open inbound traffic from outside of the sandbox. The syntax is port[single/range]:protocol [tcp(default)/udp ].For example: “80;443:tcp;200-220:udp”"
        tags: [user_input]

      Allow all Sandbox Traffic:
        type: boolean
        default: true
        description: "Whether an app should allow inbound traffic from all other apps in the sandbox. If set to false, access from specific apps or subnets can be defined by an API call."
        tags: [user_input]

      Enable IP Forwarding:
        type: boolean
        default: false
        description: "Enables IP forwarding on all network interfaces of the app in order to support virtual appliances like routers and firewalls that are connected to multiple subnets."

    artifacts:
      icon:
        file: azure-custom-image-icon.png
        type: tosca.artifacts.File
