SHELL_NAME = "Microsoft Azure 2nd Gen"

AZURE_VM_FROM_MARKETPLACE_DEPLOYMENT_PATH = f"{SHELL_NAME}.Azure VM From Marketplace 2nd Gen"
AZURE_VM_FROM_CUSTOM_IMAGE_DEPLOYMENT_PATH = f"{SHELL_NAME}.Azure VM from Custom Image 2nd Gen"
