SHELL_NAME = "Microsoft Azure 2G"

AZURE_VM_FROM_MARKETPLACE_DEPLOYMENT_PATH = f"{SHELL_NAME}.Azure VM From Marketplace 2G"
AZURE_VM_FROM_CUSTOM_IMAGE_DEPLOYMENT_PATH = f"{SHELL_NAME}.Azure VM From Custom Image 2G"
